### ISSUE TITLE
Any saved Changes that is made in questions in the Survey after publish is not reflected.

### ISSUE THREAD

**Issue by Premraj-Murugaraj** [Premraj-Murugaraj/Cusjo_Template#30]
Steps:
>Click edit survey
>Go to Module 9
>Uncheck tags
>CLick Save
>Changes not reflected.

<img width="941" alt="issue_4" src="https://cloud.githubusercontent.com/assets/17523344/23289461/c7b5183a-fa84-11e6-8f10-1759572da82f.PNG">
<img width="958" alt="issue_4_1" src="https://cloud.githubusercontent.com/assets/17523344/23289459/c7b20e10-fa84-11e6-96ae-9aafe87d3f66.PNG">
<img width="936" alt="issue_4_2" src="https://cloud.githubusercontent.com/assets/17523344/23289460/c7b323b8-fa84-11e6-900a-2263f5fbc283.PNG">
<img width="960" alt="issue_4_3" src="https://cloud.githubusercontent.com/assets/17523344/23289462/c7be1174-fa84-11e6-8fbc-2000b952a780.png">

**Comment by privin** [comment]
fixed

**Comment by Premraj-Murugaraj** [comment]
fixed
